# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Weiwei Jia
email: weiwei.jia@student.kyh.se
description: > # this means to ignore newlines until "baseurl:"
  7235.49km between Xi'an and Stockholm; 10h by flight;but just one click find you me here
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  weiweijia

# Build settings
markdown: kramdown
